"""add_is_full_access_to_users

Revision ID: 1a6e7cce136d
Revises: cbf225ce8598
Create Date: 2026-04-12 18:28:57.394989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6e7cce136d'
down_revision: Union[str, None] = 'cbf225ce8598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add as nullable so existing rows aren't rejected
    op.add_column('users', sa.Column('is_full_access', sa.Boolean(), nullable=True))
    # Step 2: Backfill all existing rows to False
    op.execute("UPDATE users SET is_full_access = FALSE WHERE is_full_access IS NULL")
    # Step 3: Now enforce NOT NULL
    op.alter_column('users', 'is_full_access', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_full_access')
    # ### end Alembic commands ###
