"""add_department_id_to_users

Revision ID: abc123add_dept_id
Revises: ba06b9d761d3
Create Date: 2026-09-15

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc123add_dept_id'
down_revision: Union[str, None] = 'ba06b9d761d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add department_id column to users table
    op.add_column('users', sa.Column('department_id', sa.UUID(), nullable=True))
    # Add foreign key constraint
    op.create_foreign_key('fk_users_department_id', 'users', 'departments', ['department_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_department_id', 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    # ### end Alembic commands ###
