"""Add permissions and invited_by to admin_users

Revision ID: cbf225ce8598
Revises: 1739b8ef22c5
Create Date: 2026-03-29 17:33:19.916892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbf225ce8598'
down_revision: Union[str, None] = '1739b8ef22c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('permissions', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('admin_users', sa.Column('invited_by_email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'invited_by_email')
    op.drop_column('admin_users', 'permissions')
    # ### end Alembic commands ###
